verbose: false
instrumentation:
  root: ./src
  compact: true
  include-all-sources: true
reporting:
  print: summary
  reports:
    - html
    - lcovonly
  dir: ./coverage
hooks:
  hook-run-in-context: false
  handle-sigint: false
